using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;

namespace TrafficView
{
    internal sealed partial class TrafficPopupForm
    {
        private const int BaseClientWidth = 102;
        private const int BaseClientHeight = 56;
        private const int BaseLeftOnlyClientWidth = 62;
        private const int BaseRightOnlyClientWidth = 58;
        private const int BaseWindowCornerRadius = 14;
        private const int BaseOuterInset = 2;
        private const int BaseSeparatorY = 28;
        private const int BaseSeparatorInset = 14;
        private const int BasePopupMargin = 10;
        private const int BaseCaptionX = 6;
        private const int BaseDownloadCaptionY = 9;
        private const int BaseDownloadValueX = 16;
        private const int BaseDownloadValueY = 7;
        private const int BaseUploadCaptionY = 32;
        private const int BaseUploadValueX = 16;
        private const int BaseUploadValueY = 30;
        private const int BaseCaptionWidth = 12;
        private const int BaseCaptionHeight = 8;
        private const int BaseValueWidth = 42;
        private const int BaseValueHeight = 14;
        private const int BaseMeterDiameter = 39;
        private const int BaseMeterRightInset = 5;
        private const int MiniGraphMeterDiameter = 46;
        private const int MiniGraphMeterRightInset = 3;
        private const int SimpleMeterDiameter = 42;
        private const int SimpleMeterRightInset = 5;
        private const int SimpleSparklineLeft = 10;
        private const int SimpleSparklineTop = 41;
        private const int SimpleSparklineHeight = 5;
        private const int BaseDragThreshold = 4;
        private const int BasePopupVisibleMargin = 8;
        private const int TaskbarMonitorIntervalMs = 350;
        private const int TaskbarRefreshDebounceMs = 220;
        private const int TaskbarInsetThickness = 2;
        private const int MinimumVisibleTaskbarThickness = 8;
        private const int TaskbarPlacementMargin = 2;
        private const int TaskbarOccupiedSafetyPadding = 4;
        private const int TaskbarProtectedEdgeProbe = 96;
        private const int TaskbarCompactRestoreHysteresis = 12;
        private const int TaskbarSectionToggleDragThreshold = 10;
        private const int TaskbarDesktopSnapHoldDistance = 18;
        private const int TaskbarDragSnapDistance = 36;
        private const int TaskbarDragBreakThroughDepth = 60;
        private const int TaskbarDragSnapshotRefreshMs = 120;
        private const int ManualDragMoveIntervalMs = 15;
        private const int NoSpaceMessageCooldownMs = 1800;
        private const int TaskbarTransientFailureGraceMs = 900;
        private const int DesktopToTaskbarBlinkSuppressionMs = 1200;
        private const byte TaskbarIntegratedPanelMaxBackgroundAlpha = 122;
        private const byte TaskbarIntegratedPanelTintAlpha = 34;
        private const byte TaskbarIntegratedPanelInnerOpacityBoostAlpha = 108;
        private const byte TaskbarIntegratedInfoPlateFillAlpha = 112;
        private const byte TaskbarIntegratedInfoPlateHighlightAlpha = 44;
        private const byte TaskbarIntegratedEdgeGradientOuterAlpha = 255;
        private const byte TaskbarIntegratedEdgeGradientLipAlpha = 255;
        private const float TaskbarIntegratedEdgeGradientWidth = 10.0F;
        private const float TaskbarIntegratedEdgeGradientLipWidth = 4.0F;
        private const float BaseFormFontSize = 7.0F;
        private const float BaseCaptionFontSize = 6.0F;
        private const float BaseValueFontSize = 10.4F;
        private const float SimpleValueFontSize = 9.2F;
        private const int WmNclButtonDown = 0xA1;
        private const int HtCaption = 0x2;
        private const int WmContextMenu = 0x007B;
        private const int WmNcHitTest = 0x0084;
        private const int WmDpiChanged = 0x02E0;
        private const int WmDisplayChange = 0x007E;
        private const int WmSettingChange = 0x001A;
        private const int HtTransparent = -1;
        private const int WsExLayered = 0x00080000;
        private const uint AbmGetTaskbarPos = 0x00000005;
        private const uint AbmGetState = 0x00000004;
        private const int AbsAutoHide = 0x1;
        private const uint SwpNoSize = 0x0001;
        private const uint SwpNoMove = 0x0002;
        private const uint SwpNoZOrder = 0x0004;
        private const uint SwpShowWindow = 0x0040;
        private const uint SwpNoActivate = 0x0010;
        private const uint SwpNoRedraw = 0x0008;
        private const uint SwpNoOwnerZOrder = 0x0200;
        private const uint SwpNoSendChanging = 0x0400;
        private const uint GwHwndNext = 2;
        private const uint GwHwndPrev = 3;
        private const int GwlStyle = -16;
        private const uint LwaAlpha = 0x2;
        private const int UlwAlpha = 0x2;
        private const byte AcSrcOver = 0x00;
        private const byte AcSrcAlpha = 0x01;
        private const int KeepTopMostRefreshIntervalMs = 1600;
        private static readonly IntPtr HwndTop = IntPtr.Zero;
        private static readonly IntPtr HwndTopMost = new IntPtr(-1);
        private static readonly Color BackgroundBlue = Color.FromArgb(18, 34, 82);
        private static readonly Color BorderColor = Color.FromArgb(18, 34, 82);
        private static readonly Color EdgeSmoothingColor = Color.FromArgb(120, 56, 84, 146);
        private static readonly Color BorderBevelHighlightColor = Color.FromArgb(132, 152, 184, 242);
        private static readonly Color BorderBevelShadowColor = Color.FromArgb(132, 8, 18, 46);
        private static readonly Color PanelSurfaceHighlightColor = Color.FromArgb(52, 128, 158, 220);
        private static readonly Color PanelSurfaceShadowColor = Color.FromArgb(42, 8, 16, 42);
        private static readonly Color PanelInnerEdgeHighlightColor = Color.FromArgb(76, 182, 208, 248);
        private static readonly Color PanelInnerEdgeShadowColor = Color.FromArgb(64, 8, 16, 40);
        private static readonly Color DividerColor = Color.FromArgb(46, 66, 116);
        private static readonly Color DownloadCaptionColor = Color.FromArgb(255, 220, 118);
        private static readonly Color DownloadValueColor = Color.FromArgb(255, 182, 28);
        private static readonly Color DownloadRingLowColor = Color.FromArgb(246, 144, 0);
        private static readonly Color DownloadRingHighColor = Color.FromArgb(255, 222, 84);
        private static readonly Color UploadCaptionColor = Color.FromArgb(170, 255, 164);
        private static readonly Color UploadValueColor = Color.FromArgb(72, 255, 96);
        private static readonly Color UploadRingLowColor = Color.FromArgb(88, 255, 116);
        private static readonly Color UploadRingHighColor = Color.FromArgb(214, 255, 214);
        private static readonly Color MeterTrackColor = Color.FromArgb(64, 94, 148);
        private static readonly Color MeterTrackInnerColor = Color.FromArgb(82, 112, 166);

        internal static string CreateTimerDiagnosticsText()
        {
            return string.Format(
                System.Globalization.CultureInfo.InvariantCulture,
                "Timers: refresh=1000 ms; animation=140 ms; top-most guard={0} ms; taskbar monitor={1} ms; taskbar debounce={2} ms; manual drag={3} ms",
                KeepTopMostRefreshIntervalMs,
                TaskbarMonitorIntervalMs,
                TaskbarRefreshDebounceMs,
                ManualDragMoveIntervalMs);
        }
        private static readonly Color MeterCenterColor = Color.FromArgb(11, 24, 60);
        private static readonly Color MeterCenterBorderColor = Color.FromArgb(84, 132, 196);
        private static readonly Color MeterDepthHighlightColor = Color.FromArgb(92, 228, 236, 255);
        private static readonly Color MeterDepthShadowColor = Color.FromArgb(88, 8, 16, 42);
        private static readonly Color MeterCenterHighlightColor = Color.FromArgb(88, 116, 146, 210);
        private static readonly Color MeterCenterShadowColor = Color.FromArgb(84, 4, 12, 28);
        private static readonly Color DownloadArrowBaseColor = Color.FromArgb(255, 188, 38);
        private static readonly Color DownloadArrowHighColor = Color.FromArgb(255, 228, 116);
        private static readonly Color UploadArrowBaseColor = Color.FromArgb(80, 255, 64);
        private static readonly Color UploadArrowHighColor = Color.FromArgb(170, 255, 140);
        private static readonly Color SparklineGuideColor = Color.FromArgb(74, 122, 156);
        private static readonly Color SparklineDownloadColor = Color.FromArgb(255, 178, 58);
        private static readonly Color SparklineUploadColor = Color.FromArgb(90, 255, 120);
        private static readonly Color SimplePanelBackgroundColor = Color.FromArgb(5, 18, 22);
        private static readonly Color SimpleBorderColor = Color.FromArgb(26, 238, 255);
        private static readonly Color SimpleDividerColor = Color.FromArgb(34, 182, 196);
        private static readonly Color SimpleDownloadCaptionColor = Color.FromArgb(255, 176, 22);
        private static readonly Color SimpleDownloadValueColor = Color.FromArgb(255, 164, 18);
        private static readonly Color SimpleDownloadRingLowColor = Color.FromArgb(255, 154, 22);
        private static readonly Color SimpleDownloadRingHighColor = Color.FromArgb(255, 220, 108);
        private static readonly Color SimpleUploadCaptionColor = Color.FromArgb(118, 255, 98);
        private static readonly Color SimpleUploadValueColor = Color.FromArgb(98, 255, 86);
        private static readonly Color SimpleUploadRingLowColor = Color.FromArgb(104, 255, 92);
        private static readonly Color SimpleUploadRingHighColor = Color.FromArgb(214, 255, 168);
        private static readonly Color SimpleMeterTrackColor = Color.FromArgb(42, 0, 230, 255);
        private static readonly Color SimpleMeterTrackInnerColor = Color.FromArgb(44, 104, 255, 92);
        private static readonly Color SimpleMeterCenterColor = Color.FromArgb(8, 24, 26);
        private static readonly Color SimpleDownloadArrowBaseColor = Color.FromArgb(255, 166, 24);
        private static readonly Color SimpleDownloadArrowHighColor = Color.FromArgb(255, 220, 110);
        private static readonly Color SimpleUploadArrowBaseColor = Color.FromArgb(104, 255, 86);
        private static readonly Color SimpleUploadArrowHighColor = Color.FromArgb(214, 255, 170);
        private static readonly Color SimpleSparklineGuideColor = Color.FromArgb(60, 44, 190, 210);
        private static readonly Color SimpleSparklineDownloadColor = Color.FromArgb(255, 166, 24);
        private static readonly Color SimpleSparklineUploadColor = Color.FromArgb(104, 255, 92);
        private static readonly StringFormat TrafficTextStringFormat = CreateTrafficTextFormat(false);
        private static readonly StringFormat TrafficEllipsisTextFormat = CreateTrafficTextFormat(true);
        private static readonly StringFormat TrafficRightAlignedTextFormat = CreateTrafficTextFormat(false, StringAlignment.Far);
        private const double LowTrafficVisualizationExponent = 0.72D;
        private const double ArrowMotionDeadZoneRatio = 0.05D;
        private const double ArrowMotionFullRatio = 0.30D;
        private const int RingSegmentCount = 18;
        private const float RingSegmentGapDegrees = 4.2F;
        private const float MinimumVisibleSegmentSweepDegrees = 0.9F;
        private const double RingDisplayRiseSmoothingFactor = 0.28D;
        private const double RingDisplayFallSmoothingFactor = 0.14D;
        private const double RingDisplayNoiseFloorBytesPerSecond = 8D * 1024D;
        private const int DisplaySmoothingSampleCount = 3;
        private const int TrafficHistorySampleCount = 60;
        private const int OverlaySparklinePointCount = 24;
        private const int MiniGraphOverlaySparklinePointCount = 40;
        private const int MiniGraphRingSegmentCount = 16;
        private const float MiniGraphRingSegmentGapDegrees = 3.2F;
        private const float MiniGraphDownloadRingSegmentGapDegrees = 0.7F;
        private const float MiniGraphUploadRingSegmentGapDegrees = 1.2F;
        private const float MiniGraphDualRingInnerGapFactor = 0.36F;
        private const float MiniSoftDualRingInnerGapFactor = 0.46F;
        private const float TaskbarIntegratedDownloadRingOutwardExpansion = 1.5F;
        private const double MiniGraphRingDisplayNoiseFloorBytesPerSecond = 2D * 1024D;
        private const double MiniGraphDownloadLowTrafficVisualizationExponent = 0.50D;
        private const double MiniGraphUploadLowTrafficVisualizationExponent = 0.58D;
        private const double MiniGraphDownloadMinimumVisualizationPeakBytesPerSecond = 96D * 1024D;
        private const double MiniGraphUploadMinimumVisualizationPeakBytesPerSecond = 128D * 1024D;
        private const float MiniGraphSparklineLeft = 8F;
        private const float MiniGraphSparklineTop = 46F;
        private const float MiniGraphSparklineHeight = 8F;
        private const float MiniGraphSparklineContentLeftInset = 0F;
        private const float PeakHoldMarkerSweepDegrees = 8.5F;
        private const double PeakHoldReleaseDelaySeconds = 0.70D;
        private const double PeakHoldDecayPerSecond = 0.42D;
        private const double MeterGlossAnimationThresholdRatio = 0.02D;
        private const double MeterGlossClockwiseMaxRotationDegreesPerSecond = 138D;
        private const double MeterGlossCounterClockwiseMaxRotationDegreesPerSecond = 110D;
        private const double ActivityBorderFadeInStartRatio = 0.008D;
        private const double ActivityBorderFadeInFullRatio = 0.165D;
        private const double ActivityBorderAnimationThresholdRatio = 0.006D;
        private const double ActivityBorderBaseRotationDegreesPerSecond = 56D;
        private const double ActivityBorderMaxRotationDegreesPerSecond = 328D;
        private const double ActivityBorderTravelPulseWidth = 0.105D;
        private const double ActivityBorderTravelTailWidth = 0.245D;
        private const float StandardMeterGlossExtraInset = 2.3F;
        private const float MiniGraphDownloadRingWeight = 1.12F;
        private const float MiniGraphUploadRingWeight = 1.00F;
        private const float MiniGraphDownloadSparklineWidthScale = 1.08F;
        private const float MiniGraphUploadSparklineWidthScale = 1.00F;
        private const int MiniGraphDownloadSparklineAreaAlpha = 38;
        private const int MiniGraphUploadSparklineAreaAlpha = 30;
        private const int MiniGraphDownloadPeakMarkerAlpha = 188;
        private const int MiniGraphUploadPeakMarkerAlpha = 176;
        private const string PanelBackgroundAssetFileName = "TrafficView.panel.png";
        private const string PanelBackgroundScaledAssetFileNameFormat = "TrafficView.panel.{0}.png";
        private const string PanelOverlayAssetFileName = "TrafficView.overlay.panel.png";
        private const string PanelOverlayScaledAssetFileNameFormat = "TrafficView.overlay.panel.{0}.png";
        private const string SimpleModeAssetDirectoryName = "Simple";
        private const string SimpleBlueModeAssetDirectoryName = "SimpleBlue";
        private static readonly double[] DisplaySmoothingWeights = new double[] { 0.15D, 0.30D, 0.55D };
        private static readonly object PanelBackgroundAssetSync = new object();
        private static readonly int[] PanelBackgroundPreparedScalePercents = new int[] { 90, 100, 110, 125, 150 };
        private static readonly Dictionary<string, Dictionary<string, Bitmap>> CachedPanelBackgroundAssetsByDirectory =
            new Dictionary<string, Dictionary<string, Bitmap>>(StringComparer.OrdinalIgnoreCase);
        private static readonly Dictionary<string, bool> PanelBackgroundAssetLoadAttemptedByDirectory =
            new Dictionary<string, bool>(StringComparer.OrdinalIgnoreCase);
        private static readonly Dictionary<string, Dictionary<string, Bitmap>> CachedPanelOverlayAssetsByDirectory =
            new Dictionary<string, Dictionary<string, Bitmap>>(StringComparer.OrdinalIgnoreCase);
        private static readonly Dictionary<string, bool> PanelOverlayAssetLoadAttemptedByDirectory =
            new Dictionary<string, bool>(StringComparer.OrdinalIgnoreCase);
        private static readonly object MeterCenterAssetSync = new object();
        private static string cachedMeterCenterAssetPath = string.Empty;
        private static Bitmap cachedMeterCenterAsset;
    }
}
